### ISSUE TITLE
Поиск комнат по bfs

### ISSUE THREAD

**Issue by Sitych** [Sitych/lemin#9]
@rretta @Pa53L , Написать функцию ft_find_bfs и ft_set_bfs

**Comment by Fanomi** [comment]
Сделано с поправкой на неправильную работу функции ft_instert_links, если конкретно — линки 971 комнаты неправильно записываются.

**Comment by Fanomi** [comment]
Функция ft_instert_links была пофикшена удаленно @Sitych, пока @rretta стримил ему код.
